var:
  my_domain_name: homeplus
  domain_owner_name: admin
  domain_owner_password: adminpassowrd

env:
  environment: dev

tasks:
  - name: Create Domain
    id: my_domain
    uses: "@modules/resource"
    spec:
      resource_type: identity.Domain
      data:
        name: ${{ self.id }}
      matches:
        - name

  - name: Create Domain Owner
    id: my_domain_owner
    uses: "@modules/resource"
    spec:
      resource_type: identity.DomainOwner
      data:
        name: ${{ env.environment}}-${{ var.domain_owner_name }}
        password: ${{ env.environment}}-${{ var.domain_owner_password }}
        domain_id: ${{ tasks.my_domain.output.domain_id }}
      matches:
        - name
        - domain_id

  - name: Read user data from excel file
    id: excel_data
    uses: "@modules/excel" # 우리의 built-in의 modules/resource
    # uses: https://github.com/spaceone/dev ... .py 등등
    spec:
      action: load
      file_path: user_info.svc
      not_exists: error

  - name: Create admin user
    if: ${{ tasks.excel_data.user.type }} ) == 'admin'
    id: admin_user
    uses: "@modules/resource"
    spec:
      resource_type: identity.User
      data:
        name: stark
        domain_id: ${{ tasks.my_domain.output.domain_id }}
        description: my name is ${{ self.spec.data.name }}
        tags:
          created_by: ${{ self.name }}
      matches:
        - name
        - domain_id