api_key: xxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxx
endpoints:
  identity: grpc://identity:50051
  inventory: grpc://inventory:50051
  secret: grpc://secret:50051
  repository: grpc://repository:50051
  plugin: grpc://plugin:50051
  monitoring: grpc://monitoring:50051
  billing: grpc://billing:50051
  statistics: grpc://statistics:50051
  config: grpc://config:50051
  power_scheduler: grpc://power-scheduler:50051
  spot_automation: grpc://spot-automation:50051