name: SpaceONE CI commit push
on:
  push:
    branches:
      - master
      - action/tag-trigger
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

env:
  IMAGE_PREFIX: pyengine
  # LOCATION points the parent directory
  LOCATION_SETUP_PY: src # optional. for pypi upload
  LOCATION_VERSION: src # the location for VERSION file (ex- . means the location of VERSION is ./VERSION)
  SERVICE: spacectl
  LOCATION_DOCKERFILE: .

jobs:
  docker:
    if: github.repository_owner == 'spaceone-dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: |
          echo "$(cat $LOCATION_VERSION/VERSION).${{ github.run_id }}">$LOCATION_VERSION/VERSION
          echo "VERSION=$(cat $LOCATION_VERSION/VERSION).${{ github.run_id }}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}/${{ env.SERVICE }}:latest
            ${{ env.IMAGE_PREFIX }}/${{ env.SERVICE }}:${{ env.VERSION }}

      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}